### ISSUE TITLE
Please update the README (cordova-plugin-iosrtc stuff)

### ISSUE THREAD

**Issue by ibc** [aoberoi/cordova-plugin-opentokjs#6]
Thanks a lot for your mention in the README. Just some bullets to update:
- The plugin ID is "cordova-plugin-iosrtc" since version 1.3.0 (released today).
- It already exposes `MediaStream` and `webkitMediaStream`.

Also, there is no 1.2.9 version but 1.3.0, so this is wrong (plugin.xml):

``` html
<dependency id="com.eface2face.iosrtc" spec="^1.2.9" />
```

Should be:

``` html
<dependency id="cordova-plugin-iosrtc" spec="^1.3.0" />
```

Thanks :)

**Comment by aoberoi** [comment]
You're welcome. Thanks for your great plugin!
